language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vkm22588/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vkm22588/docker-react npm run test